export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";

//POST

export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

//GET

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

//patch

export const PATCH_PRODUCT_SUCCESS = "PATCH_PRODUCT_SUCCESS";

//delete

export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const DELETE_PRODUCT_LOADING = "DELETE_PRODUCT_LOADING";

export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";