export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const SET_DECREMENT= "SET_DECREMENT"
export const SET_INCREMENT= "SET_INCREMENT"
export const CLEAR_CART= "CLEAR_CART"
export const CART_ITEM_PRICE_TOTAL= "CART_ITEM_PRICE_TOTAL"
